// ignore_for_file: constant_identifier_names

abstract final class SettingBoxKey {
  static const String btmProgressBehavior = 'btmProgressBehavior',
      defaultVideoQa = 'defaultVideoQa',
      defaultVideoQaCellular = 'defaultVideoQaCellular',
      defaultAudioQa = 'defaultAudioQa',
      defaultAudioQaCellular = 'defaultAudioQaCellular',
      autoPlayEnable = 'autoPlayEnable',
      fullScreenMode = 'fullScreenMode',
      preferCodecs = 'preferCodecs',
      preferCodecsCellular = 'preferCodecsCellular',
      defaultToastOp = 'defaultToastOp',
      defaultPicQa = 'defaultPicQa',
      enableHA = 'enableHA',
      audioOutput = 'audioOutput',
      bufferSize = 'bufferSize',
      bufferSec = 'bufferSec',
      hardwareDecoding = 'hardwareDecoding',
      videoSync = 'videoSync',
      autosync = 'autosync',
      p1080 = 'p1080',
      enableAutoEnter = 'enableAutoEnter',
      enableAutoExit = 'enableAutoExit',
      enableOnlineTotal = 'enableOnlineTotal',
      superChatType = 'superChatType',
      fullScreenSCWidth = 'fullScreenSCWidth',
      keyboardControl = 'keyboardControl',
      pauseOnMinimize = 'pauseOnMinimize',
      pgcSkipType = 'pgcSkipType',
      audioPlayMode = 'audioPlayMode',
      showBatteryLevel = 'showBatteryLevel',
      playerVolume = 'playerVolume',
      maxVolume = 'maxVolume';

  static const String enableVerticalExpand = 'enableVerticalExpand',
      feedBackEnable = 'feedBackEnable',
      enableLongShowControl = 'enableLongShowControl',
      horizontalScreen = 'horizontalScreen',
      CDNService = 'CDNService',
      disableAudioCDN = 'disableAudioCDN',
      autoPiP = 'autoPiP',
      enableAutoLongPressSpeed = 'enableAutoLongPressSpeed',
      useRelativeSlide = 'useRelativeSlide',
      sliderDuration = 'sliderOffset',
      enableQuickDouble = 'enableQuickDouble',
      fullScreenGestureReverse = 'fullScreenGestureReverse',
      enableBackgroundPlay = 'enableBackgroundPlay',
      continuePlayInBackground = 'continuePlayInBackground',
      appRcmd = 'appRcmd',
      enableSaveLastData = 'enableSaveLastData',
      minDurationForRcmd = 'minDurationForRcmd',
      minPlayForRcmd = 'minPlayForRcmd',
      minLikeRatioForRecommend = 'minLikeRatioForRecommend',
      exemptFilterForFollowed = 'exemptFilterForFollowed',
      banWordForRecommend = 'banWordForRecommend',
      applyFilterToRelatedVideos = 'applyFilterToRelatedVideos',
      autoUpdate = 'autoUpdate',
      maxCacheSize = 'maxCacheSize',
      defaultShowComment = 'defaultShowComment',
      replySortType = 'replySortType',
      reply2SortType = 'reply2SortType',
      defaultDynamicType = 'defaultDynamicType',
      showDynInteraction = 'showDynInteraction',
      enableHotKey = 'enableHotKey',
      enableSearchRcmd = 'enableSearchRcmd',
      enableQuickFav = 'enableQuickFav',
      enableWordRe = 'enableWordRe',
      enableSearchWord = 'enableSearchWord',
      enableSystemProxy = 'enableSystemProxy',
      enableAi = 'enableAi',
      disableLikeMsg = 'disableLikeMsg',
      defaultHomePage = 'defaultHomePage',
      previewQuality = 'previewQuality',
      checkDynamic = 'checkDynamic',
      dynamicPeriod = 'dynamicPeriod',
      schemeVariant = 'schemeVariant',
      showViewPoints = 'showViewPoints',
      showRelatedVideo = 'showRelatedVideo',
      showVideoReply = 'showVideoReply',
      showBangumiReply = 'showBangumiReply',
      alwaysExpandIntroPanel = 'alwaysExapndIntroPanel',
      expandIntroPanelH = 'exapndIntroPanelH',
      horizontalSeasonPanel = 'horizontalSeasonPanel',
      horizontalMemberPage = 'horizontalMemberPage',
      replyLengthLimit = 'replyLengthLimit',
      showArgueMsg = 'showArgueMsg',
      reverseFromFirst = 'reverseFromFirst',
      badCertificateCallback = 'badCertificateCallback',
      continuePlayingPart = 'continuePlayingPart',
      cdnSpeedTest = 'cdnSpeedTest',
      horizontalPreview = 'horizontalPreview',
      banWordForReply = 'banWordForReply',
      banWordForZone = 'banWordForZone',
      savedRcmdTip = 'savedRcmdTip',
      openInBrowser = 'openInBrowser',
      refreshDisplacement = 'refreshDisplacement',
      showHotRcmd = 'showHotRcmd',
      audioNormalization = 'audioNormalization',
      fallbackNormalization = 'fallbackNormalization',
      superResolutionType = 'superResolutionType',
      preInitPlayer = 'preInitPlayer',
      mainTabBarView = 'mainTabBarView',
      searchSuggestion = 'searchSuggestion',
      showDecorate = 'showDynDecorate',
      showMedal = 'showMedal',
      enableLivePhoto = 'enableLivePhoto',
      showSeekPreview = 'showSeekPreview',
      showDmChart = 'showDmChart',
      enableCommAntifraud = 'enableCommAntifraud',
      biliSendCommAntifraud = 'biliSendCommAntifraud',
      enableCreateDynAntifraud = 'enableCreateDynAntifraud',
      coinWithLike = 'coinWithLike',
      isPureBlackTheme = 'isPureBlackTheme',
      antiGoodsDyn = 'antiGoodsDyn',
      antiGoodsReply = 'antiGoodsReply',
      expandDynLivePanel = 'expandDynLivePanel',
      springDescription = 'springDescription',
      enableHttp2 = 'enableHttp2',
      slideDismissReplyPage = 'slideDismissReplyPage',
      showFSActionItem = 'showFSActionItem',
      enableShrinkVideoSize = 'enableShrinkVideoSize',
      showDynActionBar = 'showDynActionBar',
      darkVideoPage = 'darkVideoPage',
      enableSlideVolumeBrightness = 'enableSlideVolumeBrightness',
      enableSlideFS = 'enableSlideFS',
      retryCount = 'retryCount',
      retryDelay = 'retryDelay',
      liveQuality = 'liveQuality',
      liveQualityCellular = 'liveQualityCellular',
      fastForBackwardDuration = 'fastForBackwardDuration',
      recordSearchHistory = 'recordSearchHistory',
      showPgcTimeline = 'showPgcTimeline',
      pageTransition = 'pageTransition',
      optTabletNav = 'optTabletNav',
      banWordForDyn = 'banWordForDyn',
      enableLog = 'enableLog',
      memberTab = 'memberTab',
      dynamicDetailRatio = 'dynamicDetailRatio',
      directExitOnBack = 'directExitOnBack',
      quickFavId = 'quickFavId',
      showFsScreenshotBtn = 'showFsScreenshotBtn',
      showFsLockBtn = 'showFsLockBtn',
      silentDownImg = 'silentDownImg',
      showMemberShop = 'showMemberShop',
      enablePlayAll = 'enablePlayAll',
      enableTapDm = 'enableTapDm',
      setSystemBrightness = 'setSystemBrightness',
      downloadPath = 'downloadPath',
      imageSavePath = 'imageSavePath',
      followOrderType = 'followOrderType',
      enableImgMenu = 'enableImgMenu',
      showDynDispute = 'showDynDispute',
      touchSlopH = 'touchSlopH',
      floatingNavBar = 'floatingNavBar',
      removeSafeArea = 'removeSafeArea',
      angleDegrees = 'angleDegrees',
      liveStream = 'liveStream',
      enableDocProvider = 'enableDocProvider',
      enableEmoteTooltip = 'enableEmoteTooltip';

  static const String minimizeOnExit = 'minimizeOnExit',
      windowSize = 'windowSize',
      windowPosition = 'windowPosition',
      isWindowMaximized = 'isWindowMaximized',
      showWindowTitleBar = 'showWindowTitleBar',
      desktopVolume = 'desktopVolume',
      showTrayIcon = 'showTrayIcon',
      uiScale = 'uiScale';

  static const String subtitlePreferenceV2 = 'subtitlePreferenceV2',
      enableDragSubtitle = 'enableDragSubtitle',
      subtitlePaddingH = 'subtitlePaddingH',
      subtitlePaddingB = 'subtitlePaddingB',
      subtitleBgOpacity = 'subtitleBgOpaticy',
      subtitleStrokeWidth = 'subtitleStrokeWidth',
      subtitleFontScale = 'subtitleFontScale',
      subtitleFontScaleFS = 'subtitleFontScaleFS',
      subtitleFontWeight = 'subtitleFontWeight';

  static const String webdavUri = 'webdavUri',
      webdavUsername = 'webdavUsername',
      webdavPassword = 'webdavPassword',
      webdavDirectory = 'webdavDirectory';

  static const String enableSponsorBlock = 'enableSponsorBlock',
      blockSettings = 'blockSettings',
      blockLimit = 'blockLimit',
      blockColor = 'blockColor',
      blockUserID = 'blockUserID',
      blockToast = 'blockToast',
      blockServer = 'blockServer',
      blockTrack = 'blockTrack';

  static const String enableShowDanmaku = 'enableShowDanmaku',
      enableShowLiveDanmaku = 'enableShowLiveDanmaku',
      pipNoDanmaku = 'pipNoDanmaku',
      showVipDanmaku = 'showVipDanmaku',
      mergeDanmaku = 'mergeDanmaku',
      danmakuWeight = 'danmakuWeight',
      danmakuBlockType = 'danmakuBlockType',
      danmakuShowArea = 'danmakuShowArea',
      danmakuOpacity = 'danmakuOpacity',
      danmakuFontScale = 'danmakuFontScale',
      danmakuFontScaleFS = 'danmakuFontScaleFS',
      danmakuDuration = 'danmakuDuration',
      danmakuStaticDuration = 'danmakuStaticDuration',
      danmakuMassiveMode = 'danmakuMassiveMode',
      danmakuFixedV = 'danmakuFixedV',
      danmakuStatic2Scroll = 'danmakuStatic2Scroll',
      danmakuLineHeight = 'danmakuLineHeight',
      danmakuStrokeWidth = 'strokeWidth',
      danmakuFontWeight = 'fontWeight';

  static const String systemProxyHost = 'systemProxyHost',
      systemProxyPort = 'systemProxyPort';

  static const String themeMode = 'themeMode',
      defaultTextScale = 'textScale',
      appFontWeightV2 = 'appFontWeightV2',
      dynamicColor = 'dynamicColor',
      customColor = 'customColor',
      displayMode = 'displayMode',
      smallCardWidth = 'smallCardWidth',
      recommendCardWidth = 'recommendCardWidth',
      dynamicsWaterfallFlow = 'dynamicsWaterfallFlow',
      upPanelPosition = 'upPanelPosition',
      dynamicsShowAllFollowedUp = 'dynamicsShowAllFollowedUp',
      useSideBar = 'useSideBar',
      enableMYBar = 'enableMYBar',
      hideTopBar = 'hideSearchBar',
      hideBottomBar = 'hideTabBar',
      barHideType = 'barHideType',
      tabBarSort = 'tabBarSort',
      dynamicBadgeMode = 'dynamicBadgeMode',
      msgBadgeMode = 'msgBadgeMode',
      msgUnReadTypeV2 = 'msgUnReadTypeV2',
      navBarSort = 'navBarSort',
      tempPlayerConf = 'tempPlayerConf',
      reduceLuxColor = 'reduceLuxColor',
      liveCdnUrl = 'liveCdnUrl',
      saveReply = 'saveReply',
      appFont = 'appFont';
}

/// 不参与导出的设置键（`GStorage.exportAllSettings` 会剔除，导入时保留本机原值）。
///
/// 这些键的「正确取值」取决于**当前这台设备、当前这个网络、当前这份凭据或当前这套
/// 窗口布局**，把另一台设备上的取值搬过来只会制造故障：真机反馈表明，用 WebDAV 同步
/// 设置后会出现「画中画黑屏 / 取流失败」，而同一套设置在设置页里逐项手动填写则一切正常。
abstract final class LocalOnlySettingKey {
  static const Set<String> values = {
    // 网络与线路：换一台机器或换一个网络，原值几乎必然失效
    SettingBoxKey.enableSystemProxy,
    SettingBoxKey.systemProxyHost,
    SettingBoxKey.systemProxyPort,
    SettingBoxKey.CDNService,
    SettingBoxKey.disableAudioCDN,
    SettingBoxKey.liveCdnUrl,
    SettingBoxKey.enableHttp2,
    SettingBoxKey.badCertificateCallback,
    // 播放器在本机上的能力取值：与本机编解码器、屏幕刷新率绑定
    SettingBoxKey.hardwareDecoding,
    SettingBoxKey.videoSync,
    SettingBoxKey.preferCodecs,
    SettingBoxKey.preferCodecsCellular,
    // 画中画与后台播放：三者必须同机自洽——`autoPiP` 同时是 iOS 的后台保活判据
    // （`isIOSPipKeepingAlive`），跨设备同步只会造出互相打架的组合
    SettingBoxKey.autoPiP,
    SettingBoxKey.continuePlayInBackground,
    SettingBoxKey.enableBackgroundPlay,
    // 本机路径与凭据
    SettingBoxKey.downloadPath,
    SettingBoxKey.imageSavePath,
    SettingBoxKey.webdavUri,
    SettingBoxKey.webdavUsername,
    SettingBoxKey.webdavPassword,
    SettingBoxKey.webdavDirectory,
    // 桌面窗口布局：只对取备份的那台机器有意义
    SettingBoxKey.minimizeOnExit,
    SettingBoxKey.windowSize,
    SettingBoxKey.windowPosition,
    SettingBoxKey.isWindowMaximized,
    SettingBoxKey.showWindowTitleBar,
    SettingBoxKey.desktopVolume,
    SettingBoxKey.showTrayIcon,
    SettingBoxKey.uiScale,
  };

  static bool contains(Object? key) => values.contains('$key');
}

abstract final class LocalCacheKey {
  static const String historyPause = 'historyPause',
      blackMids = 'blackMids',
      danmakuFilterRules = 'danmakuFilterRules',
      mixinKey = 'mixinKey',
      timeStamp = 'timeStamp',
      buvid = 'buvid';
}

abstract final class VideoBoxKey {
  static const String playRepeat = 'playRepeat',
      playSpeedDefault = 'playSpeedDefault',
      longPressSpeedDefault = 'longPressSpeedDefault',
      speedsList = 'speedsList',
      cacheVideoFit = 'cacheVideoFit';
}
